#**Universal Functions**



In [1]:
import numpy as np

In [2]:
num = np.array([1, 4, 9, 16, 25, 36])

Array arithmetic

In [3]:
np.sqrt(num)

array([1., 2., 3., 4., 5., 6.])

In [4]:
num2 = np.arange(1, 7) * 10

In [5]:
num2

array([10, 20, 30, 40, 50, 60])

In [6]:
np.add(num, num2)

array([11, 24, 39, 56, 75, 96])

In [7]:
np.multiply(num2, 5)

array([ 50, 100, 150, 200, 250, 300])

In [8]:
num3 = num2.reshape(2, 3)

In [9]:
num3

array([[10, 20, 30],
       [40, 50, 60]])

In [10]:
num4 = np.array([2, 4, 6])

In [12]:
np.multiply(num3, num4)

array([[ 20,  80, 180],
       [ 80, 200, 360]])

Exponents and logarithms

In [14]:
np.exp(num4)

array([  7.3890561 ,  54.59815003, 403.42879349])

In [16]:
 np.power(3, num4)

array([  9,  81, 729])

In [17]:
np.log10(num4)

array([0.30103   , 0.60205999, 0.77815125])

Trigonometric functions

In [18]:
theta = np.linspace(0, np.pi, 3)

In [19]:
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [20]:
np.cos(theta)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [21]:
np.tan(theta)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

#**Indexing and Slicing**

Indexing with One-Dimensional arrays

In [23]:
num[::]

array([ 1,  4,  9, 16, 25, 36])

In [25]:
num[2:5]

array([ 9, 16, 25])

In [26]:
num[::-1]

array([36, 25, 16,  9,  4,  1])

In [29]:
num[-4:-2]

array([ 9, 16])

In [30]:
num[-3]

16

Indexing with Two-Dimensional arrays

In [31]:
grades = np.array([[87, 96, 70], [100, 87, 90],
                   [94, 77, 90], [100, 81, 82]])

In [32]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [33]:
grades[1, 0] # row 1, column 0

100

In [35]:
grades[2] #select a single row, specify only one index in square brackets

array([94, 77, 90])

In [36]:
grades[0:2] #select multiple sequential rows, use slice notation

array([[ 87,  96,  70],
       [100,  87,  90]])

In [38]:
grades[[1, 3]]#select multiple non-sequential rows, use a list of row indices

array([[100,  87,  90],
       [100,  81,  82]])

In [39]:
grades[:, 0]#Selecting a Subset of a Two-Dimensional array’s Columns

array([ 87, 100,  94, 100])

In [40]:
grades[:, 1:3]#representing a subset of the rows

array([[96, 70],
       [87, 90],
       [77, 90],
       [81, 82]])

In [41]:
grades[:, [0, 2]]#specific columns using a list of column indices

array([[ 87,  70],
       [100,  90],
       [ 94,  90],
       [100,  82]])

#**Reshaping and Transposing**

In [50]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [51]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

Reshaping

In [52]:
grades.reshape(1, 6)#Method reshape returns a view of the original array with the new dimensions.

array([[ 87,  96,  70, 100,  87,  90]])

In [53]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [54]:
grades.resize(1, 6)#Method resize modifies the original array’s shape

In [55]:
grades

array([[ 87,  96,  70, 100,  87,  90]])

Transposing

In [56]:
grades.T

array([[ 87],
       [ 96],
       [ 70],
       [100],
       [ 87],
       [ 90]])

In [57]:
grades

array([[ 87,  96,  70, 100,  87,  90]])